# Generated by Django 4.2.7 on 2023-12-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('current_datetimes', models.DateTimeField(auto_now=True)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='client_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=50)),
                ('modelno', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('fueltype', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=100)),
                ('engine_size', models.CharField(max_length=100)),
                ('Mileage', models.CharField(max_length=50)),
                ('Warranty', models.CharField(max_length=100)),
                ('seating_capacity', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=100)),
                ('fueltank', models.CharField(max_length=50)),
            ],
        ),
    ]
