# Generated by Django 4.2.7 on 2023-12-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='current_datetimes',
        ),
        migrations.AddField(
            model_name='client',
            name='current_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
