# Generated by Django 4.2.7 on 2023-12-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_remove_client_current_datetimes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_car',
            name='client_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
