# Generated by Django 4.2.7 on 2023-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_client_car_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_car',
            name='subject',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
